#!/usr/bin/env python3
"""Deterministic scene → SVG/TXT/HTML. No network or rendering dependency.

Run --check to compare generated bytes without writing. Numerical fixture
validation is separate from geometry, so a plausible drawing cannot silently
replace its mathematical contract. PDF conversion lives in publication/build.py.
"""
from pathlib import Path
import argparse
import html
import json
import math
import re
import textwrap
import xml.etree.ElementTree as ET

ROOT = Path(__file__).resolve().parents[1]
INK, MUTED, BLUE, TEAL, GOLD = '#152b3c', '#465c6b', '#dcecf7', '#dcefe7', '#f4ead2'


class Drawing:
    def __init__(self, scene):
        self.items = [f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1000 720" role="img" aria-labelledby="title desc"><title id="title">{html.escape(scene["title"])}</title><desc id="desc">{html.escape(scene["alt"])}</desc>', '<rect width="1000" height="720" fill="white"/>']
        self.text(40, 38, scene['id'] + '  /  ' + scene['status'], 14, MUTED)
        self.text(40, 84, scene['title'], 30)
        self.line(40, 109, 960, 109)
        for i, line in enumerate(textwrap.wrap(scene['purpose'], 88)):
            self.text(40, 140 + 23*i, line, 19)

    def text(self, x, y, label, size=19, color=INK, anchor='start'):
        self.items.append(f'<text x="{x}" y="{y}" fill="{color}" font-family="DejaVu Sans, sans-serif" font-size="{size}" text-anchor="{anchor}">{html.escape(str(label))}</text>')

    def line(self, x, y, xx, yy, dashed=False, color=INK, width=1.5):
        dash = ' stroke-dasharray="6 5"' if dashed else ''
        self.items.append(f'<line x1="{x}" y1="{y}" x2="{xx}" y2="{yy}" stroke="{color}" stroke-width="{width}"{dash}/>')

    def arrow(self, x, y, xx, yy, dashed=False):
        self.line(x, y, xx, yy, dashed, width=2.5)
        a = math.atan2(yy-y, xx-x)
        pts = [(xx, yy), (xx-10*math.cos(a-.45), yy-10*math.sin(a-.45)), (xx-10*math.cos(a+.45), yy-10*math.sin(a+.45))]
        self.items.append('<polygon fill="'+INK+'" points="'+' '.join(f'{a:.2f},{b:.2f}' for a,b in pts)+'"/>')

    def box(self, x, y, w, h, label='', fill=BLUE, size=19):
        self.items.append(f'<rect x="{x}" y="{y}" width="{w}" height="{h}" fill="{fill}" stroke="{INK}" stroke-width="1.4"/>')
        for i, line in enumerate(label.split('\n')):
            self.text(x+14, y+29+i*25, line, size)

    def cells(self, x, y, values, width=72, fill=TEAL):
        for i, value in enumerate(values):
            self.box(x+i*width, y, width, 48, str(value), fill)

    def footer(self, scene):
        self.line(40, 608, 960, 608)
        yy = 638
        for contract in scene['contract']:
            for line in textwrap.wrap(contract, 99):
                self.text(40, yy, line, 15)
                yy += 21
        self.items.append('</svg>')
        return '\n'.join(self.items)+'\n'


def render(s, frame=None):
    d, f, k = Drawing(s), s['fixture'], s['kind']
    if k == 'tensor':
        d.text(60, 207, '01  Logical A [2,3]')
        d.cells(90, 235, f['values'][:3]); d.cells(90, 283, f['values'][3:])
        d.text(58, 268, '0'); d.text(58, 316, '1')
        d.text(355, 275, 'A[1,2] = 6')
        d.arrow(422, 300, 610, 397)
        d.text(60, 377, '02  Physical F32 storage • one owner')
        d.cells(60, 402, f['values'], 100)
        for i in range(6): d.text(75+100*i, 478, f'{i} / {4*i}', 16)
        d.text(60, 509, 'element offset / byte offset', 16)
        d.box(695, 210, 255, 140, '«struct» OwnedTensor\nshape, strides\nstorage: Vec<f32>', GOLD, 18)
        d.box(695, 424, 255, 115, '«struct» TensorView\nshape, strides, base\nborrowed &[f32]', TEAL, 18)
        d.arrow(820, 424, 820, 350, True)
        d.text(696, 383, 'borrows storage', 16)
    elif k == 'gemv':
        d.text(60, 206, '01  Select row 0 of W'); d.cells(60, 230, f['weight'][0])
        d.text(440, 206, '02  Pair the same k'); d.cells(440, 230, f['input'])
        d.text(60, 327, '03  Multiply'); d.cells(60, 350, [2,-2,1.5], 110)
        d.arrow(390, 374, 477, 374)
        d.box(490, 339, 440, 82, '04  Accumulate in k order\n0 + 2 − 2 + 1.5 = 1.5', GOLD)
        d.box(60, 468, 870, 95, '05  Repeat for row 1: 8 − 5 + 3 = 6\ny [2] = [1.5, 6] • new owner; W and x remain immutable', TEAL)
    elif k == 'pipeline':
        d.box(45, 223, 260, 92, '01  Lookup E[1,:]\nx = [1, −1, 2, 0.5]', GOLD)
        d.arrow(305, 270, 380, 270)
        d.box(390, 223, 260, 92, '02  RMSNorm\nw [4], ε = 10⁻⁵', TEAL)
        d.text(690, 244, 'Implemented through', 17); d.text(690, 272, 'Chapter 7', 17)
        d.arrow(520, 315, 520, 355)
        d.line(180, 355, 820, 355, dashed=True)
        for x, label in [(60,'Q'),(380,'K'),(700,'V')]:
            d.arrow(x+120, 355, x+120, 405, True)
            d.box(x, 410, 240, 118, f'03  W{label} [4,4]\n{label} flat [4]\n{label} heads [2,2]', BLUE)
        d.text(60, 574, 'QKV is a planned Chapter 8 operator; arrows below RMSNorm are a specification.', 17)
    elif k == 'heads':
        d.text(60, 211, '01  Flat activation • contiguous [4]')
        d.cells(60, 239, f['flat'], 130)
        d.text(60, 344, '02  Change metadata only'); d.arrow(550, 306, 550, 384)
        d.cells(60, 384, f['flat'][:2],130); d.cells(60,432,f['flat'][2:],130)
        d.text(354, 415, 'head 0: elements 0,1')
        d.text(354, 466, 'head 1: elements 2,3')
        d.box(60, 510, 870, 65, 'Same buffer • [4] stride [1] becomes [2,2] strides [2,1]', GOLD)
    elif k == 'rope':
        for p in range(4):
            x, y = 150+235*p, 328
            d.text(x-88, 211, f'p = {p}; θ = {p*30}°', 19)
            d.line(x-85,y,x+85,y); d.line(x,y-100,x,y+95)
            d.items.append(f'<circle cx="{x}" cy="{y}" r="74" fill="none" stroke="#8b9ba5"/>')
            d.arrow(x,y,x+74,y,True)
            theta = p*f['omega']
            d.arrow(x,y,x+74*math.cos(theta),y-74*math.sin(theta))
            d.text(x-92, 469, f'({math.cos(theta):.3f}, {math.sin(theta):.3f})', 18)
            if frame == p: d.box(x-90, 498, 190, 43, 'Current position', GOLD, 16)
        d.text(60, 579, 'Dashed: original pair • solid: rotated pair • circle: preserved unit norm', 18)
    elif k == 'attention':
        labels=[('01  Query and keys','q = [√2, 0]\nK = [[0,1],[1,0],[9,9]]'),('02  Dot and scale','Kq / √2\n[0, 1, 9]'),('03  Causal visibility','t = 1: positions 0,1 visible\n[0, 1, −∞]'),('04  Softmax','subtract max, exp, divide\nα ≈ [0.269, 0.731, 0]'),('05  Weight V rows','0.269[2,0] + 0.731[0,4]\nfuture [99,99] contributes 0'),('06  One head output','o ≈ [0.538, 2.924]\noutput shape [2]')]
        for i,(title,body) in enumerate(labels):
            col,row=i%3,i//3
            d.box(40+320*col,204+187*row,300,145,title+'\n'+body, TEAL if row else BLUE,17)
        d.text(40, 582, 'Order: left to right, then next row. One head; output projection and residual follow later.',16)
    elif k == 'cache':
        for p in range(4):
            yy=202+94*p
            d.text(45,yy+29,f'T = {p+1}',20)
            d.cells(165,yy,[f'K{j}' for j in range(p+1)],100,BLUE)
            d.cells(590,yy,[f'V{j}' for j in range(p+1)],85,TEAL)
            d.text(165, yy+72, f'{16*(p+1)} bytes valid • each cell holds Dₕ=2 F32 elements',15)
            if frame == p: d.line(43,yy+78,960,yy+78,width=3)
    elif k == 'batch':
        for j in range(4): d.text(235+174*j,211,f'iteration {j}',17)
        for i,row in enumerate(f['rows']):
            d.text(55,289+85*i,f'Request {chr(65+i)}',19)
            for j,v in enumerate(row):
                d.box(228+174*j,257+85*i,150,61,v, GOLD if v=='P' else TEAL if v=='D' else '#f2f4f5',24)
                if frame==j: d.line(228+174*j,325+85*i,378+174*j,325+85*i,width=3)
        d.box(55,524,873,60,'At iteration 3: A released; B and C each contribute one decode token.',BLUE,18)
    elif k == 'sequence':
        xs=[115,345,625,875]
        for x,label in zip(xs,['API','Submit queue','Worker','Context']):
            d.box(x-74,196,148,48,label,BLUE,17); d.line(x,244,x,577,True)
        messages=[(0,1,'submit(request)',285,False),(1,2,'admit / drain',337,False),(2,3,'decode_batch',398,False),(3,2,'logits / status',454,True),(2,0,'sample → stream',520,True)]
        for a,b,label,y,dash in messages:
            d.arrow(xs[a],y,xs[b],y,dash); d.text(min(xs[a],xs[b])+10,y-12,label,17)
    elif k == 'architecture':
        for x,label in [(45,'Client'),(285,'API'),(525,'Dispatcher'),(765,'Batched worker')]:
            d.box(x,209,190,64,label,BLUE,18)
            if x<765: d.arrow(x+190,241,x+232,241,True)
        d.box(45,327,230,107,'Model weights\nimmutable / shared\nGGUF → llama.cpp',GOLD,17)
        d.box(355,327,280,107,'llama.cpp graph\noperators → backend\nCPU / optional GPU',TEAL,17)
        d.box(725,327,230,107,'Context / KV\nworker-owned state\nper-model lifetime',GOLD,17)
        d.arrow(860,273,860,327); d.arrow(725,379,635,379); d.arrow(275,379,355,379)
        d.box(45,483,910,102,'PREVIEW: Dispatcher → paged runtime → explicit block ownership + packed bridge\nLIBRARY: native kernel / expert-storage components; integration must be verified\nToken results return through worker → API → client; failure finalizes request state.', '#f2f4f5',17)
    return d.footer(s)


def validate_fixture(s):
    f,k=s['fixture'],s['kind']
    if k=='tensor':
        assert sum(i*j for i,j in zip(f['index'],f['strides']))==f['element_offset']
        assert f['byte_offset']==4*f['element_offset']
    elif k=='gemv':
        assert [math.fsum(a*b for a,b in zip(row,f['input'])) for row in f['weight']]==f['output']
    elif k=='heads': assert len(f['flat'])==f['heads']*f['head_dimension']
    elif k=='rope':
        for p in f['positions']:
            a=p*f['omega']; assert math.isclose(math.cos(a)**2+math.sin(a)**2,1,abs_tol=1e-14)
    elif k=='attention':
        scores=[math.fsum(a*b for a,b in zip(f['query'],row))/math.sqrt(2) for row in f['keys'][:f['position']+1]]
        weights=[math.exp(x-max(scores)) for x in scores]; total=math.fsum(weights)
        prob=[x/total for x in weights]+[0]
        assert all(math.isclose(a,b,abs_tol=1e-12) for a,b in zip(prob,f['probabilities']))
        output=[math.fsum(p*row[j] for p,row in zip(prob,f['values'])) for j in range(2)]
        assert all(math.isclose(a,b,abs_tol=1e-12) for a,b in zip(output,f['output']))
    elif k=='cache': assert [2*f['layers']*t*f['kv_heads']*f['head_dimension']*f['bytes_per_element'] for t in f['lengths']]==[16,32,48,64]
    elif k=='batch': assert [row[-1] for row in f['rows']]==['·','D','D']


def animation(s):
    sections=[]
    for n in s['frames']:
        svg=render(s,n).replace('id="title"',f'id="title{n}"').replace('id="desc"',f'id="desc{n}"').replace('title desc',f'title{n} desc{n}')
        sections.append('<section class="frame" '+('hidden' if n else '')+'>'+svg+'</section>')
    frames=''.join(sections)
    return '<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>'+html.escape(s['title'])+'</title><style>body{font:18px system-ui;margin:1rem auto;max-width:1000px;color:#152b3c}svg{width:100%;height:auto}button,input{font:inherit;min-height:44px}button:focus-visible,input:focus-visible{outline:3px solid #163d70}p{line-height:1.5}</style><main><h1>'+html.escape(s['title'])+'</h1><button id="play" type="button">Play</button> <button id="prev" type="button">Previous</button> <button id="next" type="button">Next</button> <label>Frame <input id="step" type="range" min="0" max="3" value="0"></label><output id="state" aria-live="polite">Frame 1 of 4</output>'+frames+'<p>'+html.escape(s['caption'])+'</p><p><a href="'+s['kind']+'.svg">Complete static explanation</a> · '+html.escape(s['status'])+'</p></main><script src="player.js"></script></html>\n'


def main():
    parser=argparse.ArgumentParser(); parser.add_argument('--check',action='store_true'); args=parser.parse_args()
    manifest=json.loads((ROOT/'figures/manifest.json').read_text()); seen=set(); outputs={}
    for entry in manifest['figures']:
        assert entry['id'] not in seen, 'duplicate ID'; seen.add(entry['id'])
        for field in ['id','chapter','title','purpose','concepts','source','generated','caption','alt','evidence']: assert entry[field], field
        s=json.loads((ROOT/entry['source']).read_text()); assert s['id']==entry['id']
        assert s['caption']==entry['caption'] and s['alt']==entry['alt']
        assert (ROOT/entry['evidence']).is_file()
        if s['legacy']: assert (ROOT/s['legacy']).is_file()
        validate_fixture(s)
        svg=render(s); ET.fromstring(svg)
        base='figures/generated/'+s['kind']
        outputs[base+'.svg']=svg
        maps={
            'tensor':['logical A[1,2] ──▶ offset 3×1+2 = 5 ──▶ byte offset 20', 'owner [1 2 3 4 5 6] ◁── immutable TensorView'],
            'gemv':['W row [1 2 3] × x [2 −1 0.5]', '          ║ matched-index products', '          ▼', '       [2 −2 1.5] ──▶ sum in order ──▶ y₀ = 1.5'],
            'pipeline':['token 1 ──▶ E[1,:] ══▶ x [4] ══▶ RMSNorm ══▶ x̂ [4]', '                                                 ├┄┄▶ Wq ══▶ Q [2,2]', '                                                 ├┄┄▶ Wk ══▶ K [2,2]', '                                                 └┄┄▶ Wv ══▶ V [2,2]'],
            'heads':['flat [−1.5 3.5 −1 3] ──▷ same storage, new metadata', 'head 0 [−1.5 3.5]       head 1 [−1 3]'],
            'rope':['p=0 (1,0) ──▶ p=1 (.866,.5) ──▶ p=2 (.5,.866) ──▶ p=3 (0,1)', 'Each state applies R(pω) to the original pair; arrows order positions.'],
            'attention':['Q,K ══▶ dot / √2 ──▶ causal mask ──▶ softmax ──▶ weighted V', '        [0,1,9]      [0,1,−∞]       [.269,.731,0]   [.538,2.924]'],
            'cache':['T=1  K0             V0', 'T=2  K0 K1          V0 V1', 'T=3  K0 K1 K2       V0 V1 V2', 'T=4  K0 K1 K2 K3    V0 V1 V2 V3'],
            'batch':['iteration   0   1   2   3', 'Request A   P   D   D   ·', 'Request B   ·   P   D   D', 'Request C   ·   ·   P   D'],
            'sequence':['API ──▶ submit queue ──▶ worker ──▶ Context::decode_batch', 'API ◀┄┄ sample/stream ◀┄┄ worker ◀┄┄ logits/status', 'Legend: solid call; dashed return; worker owns Context and Batch.'],
            'architecture':['Client ┄┄▶ API ┄┄▶ Dispatcher ┄┄▶ Batched worker [CURRENT]', '                                   │', '                                   ▼', 'parameters ══▶ llama.cpp graph ◀── context / KV state', '                     │', '                     ▼', '             backend ──▶ configured CPU / GPU', 'PREVIEW: paged runtime; LIBRARY: native components; separate integration gates.']}
        lines=[s['id'],s['title'],s['status'],'',*maps[s['kind']],'']
        for label in [s['purpose'],*s['contract'],'Fixture: '+json.dumps(s['fixture'],ensure_ascii=False)]:
            lines.extend(textwrap.wrap(label,94)); lines.append('')
        lines+=['Source: '+entry['source'],'Implementation/evidence: '+s['code']]
        outputs[base+'.txt']='\n'.join(lines)+'\n'
        if s['animate']: outputs[base+'.html']=animation(s)
        assert set(entry['generated'])=={base+'.svg',base+'.txt'}
        assert entry['animation']==(base+'.html' if s['animate'] else None)
    outputs['figures/generated/player.js']=(ROOT/'figures/player.js').read_text()
    for path,data in outputs.items():
        dest=ROOT/path
        if args.check:
            assert dest.is_file() and dest.read_text()==data, 'missing or stale: '+path
        else:
            dest.parent.mkdir(parents=True,exist_ok=True); dest.write_text(data)
    print(f'figure {"check" if args.check else "build"} passed: {len(seen)} scenes, {len(outputs)} deterministic artifacts')


if __name__=='__main__': main()
