"""Book source checks for the second edition (AUTHORING.md sections 3, 11, 12).

- The main file's chapter inputs match docs/STRUCTURE.md in reading order.
- Part I construction chapters have their own learning-outcome gates.
- Every chapter declares its status on its first line.
- Every systems chapter carries the eight-part anatomy, each part once and in order,
  with at least one mechanism section between the napkin math and the ledger.
- Systems status gates: ZERO >= 1,500 prose words; FULL and VERIFIED >= 5,000 words,
  no draft markers, a filled constraint ledger and worked problems.
- Construction FULL/VERIFIED gates: >= 1,500 words, developed sections,
  native figure, executable learning route and worked problems.
- Every referenced figure exists as native TikZ, and every figure file is used.
- The stable ch14 request trace matches the real executable, and the
  construction worked calculations are recomputed here.
- docs/STATUS.md's generated chapter table is current. Regenerate it with
  `python3 scripts/check-textbook.py --write-status` (or `make status`).
"""
import codecs
import json
import math
from pathlib import Path
import re
import subprocess
import sys

ROOT = Path(__file__).resolve().parents[1]
TEX = ROOT/"tex"
STATUSES = ("SKELETON", "ZERO", "FULL", "VERIFIED")
ANATOMY = [("opening", r"\\OpeningSection\{"), ("napkin", r"\\NapkinSection\{"),
           ("ledger", r"\\LedgerSection\b"), ("lab", r"\\LabSection\{"),
           ("happened", r"\\HappenedSection\{"), ("frontier", r"\\FrontierSection\{"),
           ("exercises", r"\\ExercisesSection\b|\\input\{worked/")]
DRAFT_MARKERS = (r"\todo{", r"\FigureIntent{", r"\LabIntent{")
STATUS_BEGIN = "<!-- chapter-status:begin (generated by scripts/check-textbook.py --write-status) -->"
STATUS_END = "<!-- chapter-status:end -->"


def fail(message):
    raise SystemExit(f"check-textbook: {message}")


def plain_title(latex):
    text = latex.replace("---", "\u2014").replace("--", "\u2013").replace("~", " ")
    return re.sub(r"\\[A-Za-z]+\{([^}]*)\}", r"\1", text).strip()


def prose_words(text):
    """Approximate prose words: drop comments, commands and inline math."""
    text = re.sub(r"(?<!\\)%.*", "", text)
    text = re.sub(r"\\begin\{(verbatim|tikzpicture)\}.*?\\end\{\1\}", " ", text, flags=re.S)
    text = text.replace("\\$", " ")  # an escaped dollar is prose, not a math delimiter
    text = re.sub(r"\$[^$]*\$", " ", text)
    text = re.sub(r"\\[A-Za-z@]+\*?(\[[^\]]*\])?", " ", text)
    return len(re.findall(r"[A-Za-z0-9][A-Za-z0-9'\u2019-]*", text))


def status_of(path):
    first = path.read_text().splitlines()[0]
    match = re.fullmatch(r"% status: (\w+)", first.strip())
    if not match or match.group(1) not in STATUSES:
        fail(f"{path.relative_to(ROOT)}: first line must be '% status: <{'|'.join(STATUSES)}>'")
    return match.group(1)


def planned_chapters():
    rows = re.findall(r"^\| (\d+) \| ([^|]+?) \| ([^|]+?) \|",
                      (ROOT/"docs/STRUCTURE.md").read_text(), re.M)
    return [(int(n), title.strip(), source.strip()) for n, title, source in rows]


def check_common(path, text):
    rel = path.relative_to(ROOT)
    assert "LegacyReplacement" not in text, rel
    assert not re.search(r"\\item\s*\\item", text), rel
    assert not re.search(r"\\input\{[^}]+\.(md|txt|svg)\}", text), rel
    assert not re.search("[\u2500-\u257f]", text), f"{rel}: box-drawing characters"


def check_chapter(number, title, path):
    rel = path.relative_to(ROOT)
    text = path.read_text()
    check_common(path, text)
    status = status_of(path)
    chapters = re.findall(r"\\chapter\{(.+?)\}\\label\{ch:([a-z0-9-]+)\}", text)
    if len(chapters) != 1:
        fail(f"{rel}: needs exactly one \\chapter{{...}}\\label{{ch:<slug>}}")
    heading, label = chapters[0]
    if plain_title(heading) != title:
        fail(f"{rel}: title {plain_title(heading)!r} differs from docs/STRUCTURE.md {title!r}")
    if not re.fullmatch(rf"ch\d\d-{re.escape(label)}", path.stem):
        fail(f"{rel}: stable source ID must be chNN-{label}.tex")
    if text.count(r"\begin{ChapterIntent}") != 1:
        fail(f"{rel}: needs one ChapterIntent")
    positions = []
    for part, pattern in ANATOMY:
        found = [m.start() for m in re.finditer(pattern, text)]
        if part == "exercises":
            found = found[:1]
        if len(found) != 1:
            fail(f"{rel}: anatomy part '{part}' must appear exactly once (found {len(found)})")
        positions.append(found[0])
    if positions != sorted(positions):
        fail(f"{rel}: anatomy parts out of order")
    mechanism = text[positions[1]:positions[2]]
    if mechanism.count(r"\section{") < 1:
        fail(f"{rel}: needs at least one mechanism \\section between napkin math and ledger")
    words = prose_words(text)
    todos = text.count(r"\todo{")
    if status == "ZERO" and words < 1500:
        fail(f"{rel}: ZERO needs at least 1,500 prose words, has {words}")
    if status in ("FULL", "VERIFIED"):
        if words < 5000:
            fail(f"{rel}: {status} needs at least 5,000 prose words, has {words}")
        for marker in DRAFT_MARKERS:
            if marker in text:
                fail(f"{rel}: {status} may not contain {marker}")
        if r"\begin{ConstraintLedger}" not in text:
            fail(f"{rel}: {status} needs a filled ConstraintLedger")
        if f"\\input{{worked/{path.stem}.tex}}" not in text:
            fail(f"{rel}: {status} needs worked problems in tex/worked/{path.stem}.tex")
    return {"number": number, "title": title, "file": str(rel), "status": status,
            "words": words, "todos": todos}


def check_construction(number, title, path):
    """A complete introductory lesson is not a compressed systems chapter."""
    text = path.read_text()
    check_common(path, text)
    status = status_of(path)
    headings = re.findall(r"\\chapter\{(.+?)\}", text)
    if len(headings) != 1 or plain_title(headings[0]) != title:
        fail(f"{path}: construction title differs from plan")
    if not re.search(r"\\label\{(?:app|ch):[a-z0-9-]+\}", text):
        fail(f"{path}: missing stable chapter label")
    words = prose_words(text)
    if status in ("FULL", "VERIFIED"):
        if words < 1500:
            fail(f"{path}: complete construction needs 1,500+ prose words, has {words}")
        if any(marker in text for marker in DRAFT_MARKERS):
            fail(f"{path}: complete construction has a draft marker")
        if text.count(r"\section{") < 5 or r"\EngineFigure{" not in text:
            fail(f"{path}: construction needs developed sections and a native figure")
        if f"\\input{{worked/{path.stem}.tex}}" not in text:
            fail(f"{path}: construction needs worked problems")
        if not any(term in text for term in ("python3", "cargo", "lab-", "Labs")):
            fail(f"{path}: construction needs an executable learning route")
    return {"number": number, "title": title, "file": str(path.relative_to(ROOT)),
            "status": status, "words": words, "todos": text.count(r"\todo{")}


def worked_problem_count(path, text):
    count = 0
    for name in re.findall(r"\\input\{worked/([^}]+?)(?:\.tex)?\}", text):
        worked = TEX/"worked"/(name+".tex")
        if not worked.is_file():
            fail(f"missing worked problems {worked.relative_to(ROOT)}")
        body = worked.read_text()
        problems = body.count(r"\textbf{Problem.")
        if problems < 3:
            fail(f"{worked.relative_to(ROOT)}: expected at least 3 problems, found {problems}")
        required_solutions = problems if path.parent.name == "foundations" else 2
        if body.count(r"\textbf{Solution") < required_solutions and name != "ch14-request-lifecycle":
            fail(f"{worked.relative_to(ROOT)}: closed problems need worked solutions")
        count += problems
    return count


def status_table(rows):
    lines = [STATUS_BEGIN,
             "| # | Chapter | Source ID | Status | Words | TODOs |",
             "| ---: | --- | --- | --- | ---: | ---: |"]
    for row in rows:
        lines.append(f"| {row['number']} | {row['title']} | {Path(row['file']).stem} | {row['status']} | {row['words']:,} | {row['todos']} |")
    lines.append(STATUS_END)
    return "\n".join(lines)


def check_executable_and_calculations():
    """First-edition gates: the real CLI trace and independent worked arithmetic."""
    engine = ROOT/"code/mini-engine"
    subprocess.run(["cargo","build","-q","-p","engine0"],cwd=engine,check=True)
    binary = engine/"target/debug/engine0"
    cases = [
        (["--trace","I like"],0,"completed:end_of_sequence",1,1),
        (["--max-tokens","1","I like"],0,"completed:max_tokens",1,1),
        (["--cancel-at","1","I like"],0,"cancelled",1,1),
        (["--fail-at","1","I like"],1,"failed:model error:",1,1),
        (["I"],0,"completed:end_of_sequence",0,0),
    ]
    results = []
    for args, code, terminal, tokens, texts in cases:
        run = subprocess.run([str(binary),*args],capture_output=True,text=True)
        assert run.returncode == code, (args,run.stderr)
        events = [s for s in run.stdout.splitlines() if s.startswith("stream ")]
        assert sum(s.startswith("stream terminal ") for s in events) == 1
        assert events[-1].startswith("stream terminal "+terminal), events
        assert sum(s.startswith("stream token[") for s in events) == tokens
        assert sum(s.startswith("stream text[") for s in events) == texts
        if texts:
            assert 'stream text[through=0] " Rust"' in events
        if "--trace" in args:
            assert run.stderr.count("ModelInvoked") == 2
            assert "values: [-0.7, 0.1, 0.40000004, 2.2]" in run.stderr
        results.append({"args":args,"exit":code,"events":events})
    # Leading spaces are part of vocabulary pieces, not optional formatting.
    invalid = subprocess.run([str(binary),"like"],capture_output=True,text=True)
    assert invalid.returncode == 2 and "no token" in invalid.stderr

    decoder = codecs.getincrementaldecoder("utf-8")("strict")
    assert decoder.decode(bytes.fromhex("e4b8")) == ""
    assert decoder.decode(bytes.fromhex("96"), final=True) == "\u4e16"
    try:
        bytes.fromhex("e4b8").decode("utf-8")
    except UnicodeDecodeError:
        pass
    else:
        raise AssertionError("Incomplete scalar unexpectedly decoded")
    hidden = [1.,-.5,2.]
    weight = [1.,-.4,.25]
    original = sum(a*b for a,b in zip(hidden,weight))+.5
    changed = sum(a*b for a,b in zip(hidden,[1.,-.4,.35]))+.5
    assert math.isclose(original,2.2) and math.isclose(changed,2.4)
    assert (12+12+4)*4 == 112 and (3+4)*4 == 28
    assert [.55/.8,.25/.8] == [.6875,.3125]
    assert [1,2,3,4,5,6][2*1+1*3] == 6
    assert 1+(3-1)*4+1 == 10
    assert (min(8,5)-4,min(8,7)-4,min(4,3)-2) == (1,3,1)
    assert 2*5*7*3 == 210
    norm = math.sqrt((3**2+4**2)/2+.5)
    assert norm == math.sqrt(13)
    assert 8*8+4*8+4*8 == 128
    assert [h//2 for h in range(4)] == [0,0,1,1]
    assert 2*2*3*2*2*4 == 192
    rotate = lambda p,z: z*complex(math.cos(p),math.sin(p))
    q,k,m,n = complex(1,2),complex(-3,.5),.7,1.2
    lhs = (rotate(m,q).conjugate()*rotate(n,k)).real
    rhs = (q.conjugate()*rotate(n-m,k)).real
    assert math.isclose(lhs,rhs,abs_tol=1e-12)
    return results


def main():
    diagrams = subprocess.run(
        [sys.executable, str(ROOT/"scripts/check-system-diagrams.py")],
        check=True, capture_output=True, text=True)
    diagram_record = json.loads(diagrams.stdout)
    sys.stderr.write(diagrams.stderr)
    subprocess.run([sys.executable, str(ROOT/"scripts/check-foundations.py")],
                   check=True)
    subprocess.run([sys.executable, "-m", "unittest", "discover", "-s",
                    str(ROOT/"code/foundations"), "-p", "test_*.py"], check=True)
    write_status = "--write-status" in sys.argv[1:]
    main_file = (TEX/"inside-the-llm-engine.tex").read_text()
    assert "\\documentclass[11pt,oneside,openany]{book}" in main_file
    inputs = re.findall(r"\\input\{((?:chapters|foundations)/[^}]+?)(?:\.tex)?\}", main_file)
    chapter_inputs = [TEX/(i+".tex") for i in inputs if i != "foundations/introduction"]
    introduction = TEX/"foundations/introduction.tex"
    for path in chapter_inputs + [introduction]:
        if not path.is_file():
            fail(f"main file inputs missing {path.relative_to(ROOT)}")
    plan = planned_chapters()
    if len(plan) != len(chapter_inputs):
        fail(f"docs/STRUCTURE.md plans {len(plan)} chapters; the main file inputs {len(chapter_inputs)}")
    if len(re.findall(r"\\part\{", main_file)) != 10 or r"\appendix" in main_file:
        fail("the main file must declare ten parts and no appendix detour")
    if [p.parent.name for p in chapter_inputs[:17]] != ["foundations"] * 17:
        fail("the seventeen construction chapters must lead the book")
    if len(plan) != 59 or [row[0] for row in plan] != list(range(1,60)):
        fail("expected the approved 59-chapter sequence")

    rows = []
    for (n, title, source), path in zip(plan, chapter_inputs):
        if source != path.stem:
            fail(f"planned source {source} differs from input {path.stem}")
        check = check_construction if path.parent.name == "foundations" else check_chapter
        rows.append(check(n, title, path))

    worked_problems = 0
    for path in chapter_inputs:
        worked_problems += worked_problem_count(path, path.read_text())

    used = set()
    for path in chapter_inputs + [introduction]:
        for figure in re.findall(r"\\EngineFigure\{([^}]+)\}", path.read_text()):
            source = TEX/"figures"/(figure+".tex")
            if not source.is_file():
                fail(f"{path.relative_to(ROOT)} uses missing figure {figure}")
            body = source.read_text()
            if "\\begin{tikzpicture}" not in body or "\\includegraphics" in body:
                fail(f"{source.relative_to(ROOT)}: figures are native TikZ")
            assert "Legacy topology" not in body
            used.add(figure)
    unused = [p.stem for p in sorted((TEX/"figures").glob("*.tex")) if p.stem not in used]
    if unused:
        fail(f"figure files not used by any chapter (a figure is kept only if it is used): {unused}")

    builder = (ROOT/"scripts/build-textbook.py").read_text()
    assert '"pandoc"' not in builder and "book-print.md" not in builder

    table = status_table(rows)
    status_path = ROOT/"docs/STATUS.md"
    status_text = status_path.read_text()
    pattern = re.compile(re.escape(STATUS_BEGIN) + r".*?" + re.escape(STATUS_END), re.S)
    if not pattern.search(status_text):
        fail("docs/STATUS.md lacks the generated chapter-status block")
    if write_status:
        status_path.write_text(pattern.sub(lambda _: table, status_text))
    elif pattern.search(status_text).group(0) != table:
        fail("docs/STATUS.md chapter table is stale; run `make status`")

    results = check_executable_and_calculations()
    by_status = {s: sum(r["status"] == s for r in rows) for s in STATUSES}
    record = {"chapters": len(rows), "by_status": by_status,
              **diagram_record,
              "construction_chapters": 17, "systems_chapters": 42,
              "appendix_files": 0, "native_figures": len(used),
              "worked_problems": worked_problems,
              "chapter_words": sum(r["words"] for r in rows),
              "todos": sum(r["todos"] for r in rows), "cli_cases": results,
              "status": "structure, anatomy, figures, CLI trace and worked calculations passed"}
    output = ROOT/"build/textbook/checks.json"
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(json.dumps(record, indent=2)+"\n")
    print(json.dumps({k: v for k, v in record.items() if k != "cli_cases"}))


if __name__ == "__main__":
    main()
